In [1]:
import pandas as pd

In [2]:
df = pd.read_csv ('data/thomas_memorial_hospital_3501_20200529.csv')

In [3]:
df['Gender']=""

In [4]:
df['Race']=""

In [5]:
df['Ethnicity']=""

In [6]:
df['Code Status']=""

In [7]:
df.head()

,mrn,patient_acct_no,patient_name,patient_zip_code,date_of_birth,admission_dt,discharge_dt,service_line,sound_discharging_clinician,surprise_question,...,discharge_dx_cd,admit_dx,dx1,dx2,dx3,dx4,Gender,Race,Ethnicity,Code Status
0,J000211436,64-J000211436,"Justice, Howard",25309.0,6/20/1975,3/20/2020,3/20/2020,HM,Ananthan Krishnathas,NaN,...,G40.909,G40.909,G40.909,J01.20,E83.39,L89.91,,,,
1,J000224953,64-J000224953,"Keeling, Orville",25567.0,8/8/1944,3/20/2020,4/6/2020,HM,Rufina Nwanneka Odigwe,NaN,...,E11.9,J98.8,J98.8,C32.9,I48.91,N17.9,,,,
2,J000700032,64-J000700032,"Jones, Jessica",25702.0,2/7/1981,3/20/2020,3/27/2020,HM,Usreesha Gourneni,NaN,...,N17.9,A41.9,A41.9,M00.9,E83.42,NaN,,,,
3,J000189802,64-J000189802,"Fields, Gary",25312.0,6/11/1975,3/20/2020,3/25/2020,HM,Usreesha Gourneni,NaN,...,M70.40,A41.9,M70.40,A41.9,Z72.0,NaN,,,,
4,J000266711,64-J000266711,"Moore, James",25177.0,5/17/1957,3/20/2020,3/21/2020,HM,Ananthan Krishnathas,NaN,...,E87.1,E87.1,E87.1,R41.82,F31.9,I50.32,,,,

In [8]:
df.shape

(809, 25)

In [9]:
cols=list(df.columns.values)

In [10]:
cols

['mrn',
 'patient_acct_no',
 'patient_name',
 'patient_zip_code',
 'date_of_birth',
 'admission_dt',
 'discharge_dt',
 'service_line',
 'sound_discharging_clinician',
 'surprise_question',
 'covid_status',
 'stay_id',
 'sc_site_id',
 'hospital_name',
 'discharge_group_desc',
 'discharge_dx_cd',
 'admit_dx',
 'dx1',
 'dx2',
 'dx3',
 'dx4',
 'Gender',
 'Race',
 'Ethnicity',
 'Code Status']

In [11]:
df1=df[['mrn', 'patient_acct_no', 'patient_name', 'date_of_birth', 'admission_dt', 'discharge_dt', 'admit_dx','service_line', 'sound_discharging_clinician', 'surprise_question','patient_zip_code', 'Gender', 'Race', 'Ethnicity', 'discharge_group_desc', 'Code Status', 'covid_status']]

In [12]:
df1.head()

,mrn,patient_acct_no,patient_name,date_of_birth,admission_dt,discharge_dt,admit_dx,service_line,sound_discharging_clinician,surprise_question,patient_zip_code,Gender,Race,Ethnicity,discharge_group_desc,Code Status,covid_status
0,J000211436,64-J000211436,"Justice, Howard",6/20/1975,3/20/2020,3/20/2020,G40.909,HM,Ananthan Krishnathas,NaN,25309.0,,,,Unknown,,Not screened
1,J000224953,64-J000224953,"Keeling, Orville",8/8/1944,3/20/2020,4/6/2020,J98.8,HM,Rufina Nwanneka Odigwe,NaN,25567.0,,,,SNF,,No suspicion
2,J000700032,64-J000700032,"Jones, Jessica",2/7/1981,3/20/2020,3/27/2020,A41.9,HM,Usreesha Gourneni,NaN,25702.0,,,,Home - Private Residence,,No suspicion
3,J000189802,64-J000189802,"Fields, Gary",6/11/1975,3/20/2020,3/25/2020,A41.9,HM,Usreesha Gourneni,NaN,25312.0,,,,Home - Private Residence,,No suspicion
4,J000266711,64-J000266711,"Moore, James",5/17/1957,3/20/2020,3/21/2020,E87.1,HM,Ananthan Krishnathas,NaN,25177.0,,,,Home - Private Residence,,Not screened

In [13]:
df1.to_csv('3501_Thomas_Memorial_Hospital_20200529.csv')